create table NAFP_CFSV2_GLB_MUL_HH_TAB
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry
) PARTITION BY RANGE (D_DATETIME);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_1
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_1 FOR VALUES FROM ('1990010100') TO ('1991010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_1 on NAFP_CFSV2_GLB_MUL_HH_TAB_1 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_2
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_2 FOR VALUES FROM ('1991010100') TO ('1992010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_2 on NAFP_CFSV2_GLB_MUL_HH_TAB_2 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_3
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_3 FOR VALUES FROM ('1992010100') TO ('1993010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_3 on NAFP_CFSV2_GLB_MUL_HH_TAB_3 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_4
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_4 FOR VALUES FROM ('1993010100') TO ('1994010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_4 on NAFP_CFSV2_GLB_MUL_HH_TAB_4 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_5
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_5 FOR VALUES FROM ('1994010100') TO ('1995010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_5 on NAFP_CFSV2_GLB_MUL_HH_TAB_5 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_6
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_6 FOR VALUES FROM ('1995010100') TO ('1996010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_6 on NAFP_CFSV2_GLB_MUL_HH_TAB_6 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_7
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_7 FOR VALUES FROM ('1996010100') TO ('1997010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_7 on NAFP_CFSV2_GLB_MUL_HH_TAB_7 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_8
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_8 FOR VALUES FROM ('1997010100') TO ('1998010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_8 on NAFP_CFSV2_GLB_MUL_HH_TAB_8 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_9
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_9 FOR VALUES FROM ('1998010100') TO ('1999010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_9 on NAFP_CFSV2_GLB_MUL_HH_TAB_9 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_10
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_10 FOR VALUES FROM ('1999010100') TO ('2000010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_10 on NAFP_CFSV2_GLB_MUL_HH_TAB_10 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_11
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_11 FOR VALUES FROM ('2000010100') TO ('2001010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_11 on NAFP_CFSV2_GLB_MUL_HH_TAB_11 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_12
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_12 FOR VALUES FROM ('2001010100') TO ('2002010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_12 on NAFP_CFSV2_GLB_MUL_HH_TAB_12 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_13
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_13 FOR VALUES FROM ('2002010100') TO ('2003010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_13 on NAFP_CFSV2_GLB_MUL_HH_TAB_13 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_14
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_14 FOR VALUES FROM ('2003010100') TO ('2004010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_14 on NAFP_CFSV2_GLB_MUL_HH_TAB_14 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_15
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_15 FOR VALUES FROM ('2004010100') TO ('2005010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_15 on NAFP_CFSV2_GLB_MUL_HH_TAB_15 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_16
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_16 FOR VALUES FROM ('2005010100') TO ('2006010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_16 on NAFP_CFSV2_GLB_MUL_HH_TAB_16 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_17
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_17 FOR VALUES FROM ('2006010100') TO ('2007010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_17 on NAFP_CFSV2_GLB_MUL_HH_TAB_17 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_18
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_18 FOR VALUES FROM ('2007010100') TO ('2008010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_18 on NAFP_CFSV2_GLB_MUL_HH_TAB_18 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_19
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_19 FOR VALUES FROM ('2008010100') TO ('2009010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_19 on NAFP_CFSV2_GLB_MUL_HH_TAB_19 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_20
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_20 FOR VALUES FROM ('2009010100') TO ('2010010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_20 on NAFP_CFSV2_GLB_MUL_HH_TAB_20 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_21
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_21 FOR VALUES FROM ('2010010100') TO ('2011010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_21 on NAFP_CFSV2_GLB_MUL_HH_TAB_21 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_22
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_22 FOR VALUES FROM ('2011010100') TO ('2012010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_22 on NAFP_CFSV2_GLB_MUL_HH_TAB_22 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_23
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_23 FOR VALUES FROM ('2012010100') TO ('2013010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_23 on NAFP_CFSV2_GLB_MUL_HH_TAB_23 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_24
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_24 FOR VALUES FROM ('2013010100') TO ('2014010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_24 on NAFP_CFSV2_GLB_MUL_HH_TAB_24 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_25
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_25 FOR VALUES FROM ('2014010100') TO ('2015010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_25 on NAFP_CFSV2_GLB_MUL_HH_TAB_25 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_26
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_26 FOR VALUES FROM ('2015010100') TO ('2016010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_26 on NAFP_CFSV2_GLB_MUL_HH_TAB_26 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_27
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_27 FOR VALUES FROM ('2016010100') TO ('2017010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_27 on NAFP_CFSV2_GLB_MUL_HH_TAB_27 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_28
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_28 FOR VALUES FROM ('2017010100') TO ('2018010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_28 on NAFP_CFSV2_GLB_MUL_HH_TAB_28 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_29
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_29 FOR VALUES FROM ('2018010100') TO ('2019010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_29 on NAFP_CFSV2_GLB_MUL_HH_TAB_29 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_30
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_30 FOR VALUES FROM ('2019010100') TO ('2020010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_30 on NAFP_CFSV2_GLB_MUL_HH_TAB_30 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_31
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_31 FOR VALUES FROM ('2020010100') TO ('2021010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_31 on NAFP_CFSV2_GLB_MUL_HH_TAB_31 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_32
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_32 FOR VALUES FROM ('2021010100') TO ('2022010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_32 on NAFP_CFSV2_GLB_MUL_HH_TAB_32 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_33
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_33 FOR VALUES FROM ('2022010100') TO ('2023010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_33 on NAFP_CFSV2_GLB_MUL_HH_TAB_33 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_34
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_34 FOR VALUES FROM ('2023010100') TO ('2024010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_34 on NAFP_CFSV2_GLB_MUL_HH_TAB_34 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_35
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_35 FOR VALUES FROM ('2024010100') TO ('2025010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_35 on NAFP_CFSV2_GLB_MUL_HH_TAB_35 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_36
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_36 FOR VALUES FROM ('2025010100') TO ('2026010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_36 on NAFP_CFSV2_GLB_MUL_HH_TAB_36 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

create table NAFP_CFSV2_GLB_MUL_HH_TAB_37
(
	D_RECORD_ID serial not null,
	D_DATA_ID char(50),
	D_IYMDHM date,
	D_RYMDHM date,
	D_UPDATE_TIME timestamp,
	D_DATETIME numeric,
	D_DATETIME_MET timestamp,
	V_EVN numeric,
	D_FORETIME numeric,
	D_FORETIME_MET timestamp,
	V_LEVEL numeric,
	V_LATEND numeric,
	V_LATSTART numeric,
	V_LONEND numeric,
	V_LONSTART numeric,
	V_ELE_CODE char(50),
	V_DATA geometry,
	GEOM geometry,
	primary key(D_RECORD_ID),
	unique (D_RECORD_ID, D_DATETIME, D_FORETIME, V_LEVEL, V_EVN)
);
ALTER TABLE NAFP_CFSV2_GLB_MUL_HH_TAB ATTACH PARTITION NAFP_CFSV2_GLB_MUL_HH_TAB_37 FOR VALUES FROM ('2026010100') TO ('2027010100');
CREATE INDEX NAFP_CFSV2_GLB_MUL_HH_TAB_INDEX_37 on NAFP_CFSV2_GLB_MUL_HH_TAB_37 (D_DATETIME, V_ELE_CODE, V_LEVEL, V_EVN);

alter table NAFP_CFSV2_GLB_MUL_HH_TAB owner to postgres;

set citus.shard_count = 3;

select create_distributed_table('NAFP_CFSV2_GLB_MUL_HH_TAB', 'd_record_id');

100000 60     40000