---
- hosts: all
  tasks:
  - name: get max_connections
  - name: get shared_buffers
    shell: |
      echo -e "\nshared_buffers: `psql -p 5005 -h localhost -c 'show shared_buffers'|sed -n '3p' |awk -FM '{print$1}'|sed s/[[:space:]]//g`" >> {{ansible_dir}}/statistic.yml
    remote_user: root
  - name: get total memory
    shell: |
      echo -e "\ntotal_memory: `df . -kh |sed -n '2p'|awk '{print $2}'`" >>  {{ansible_dir}}/statistic.yml
  - name: get effective_cahe_size
  - name: get autovacuum
  - name: get default_statistics_target
  - name: get work_mem
  - name: get wal_sync_method
  - name: get wal_buffers
  - name: get constraint_exclusion
  - name: get checkpoint_timeout
  - name: get cursor_tuple_fraction
  - name: get max_prepared_transactions
  - name: autovacuum_work_mem
  - name: get wal_buffers
  - name: get autocommit
  - name: get maintenance_work_mem
  - name: get max_wal_size
  - name: get wal_level
  - name: get archive_mode
  - name: get max_wal_senders
  - name: get PostgreSQL Version